env: ''
destination: '_site'
title: "CartoDB Docs"
description: "Get the most out of CartoDB with our API, examples gallery and documentation. CartoDB is made with love by developers, for everyone"
baseurl: ""
url: "http://docs.cartodb.com"
keywords: "postgresql, postgis, vector, gis, geo, mapping, html5, developer-tools, postgres"

markdown: kramdown
# permalink: pretty
encoding: utf-8
exclude: ['README.md', 'CONTRIBUTING.md', 'config.rb', 'Gemfile', 'Gemfile.lock', 'node_modules', 'bower_components', 'Gruntfile.js', 'package.json', 'docs_build.sh', 'grunt-aws.example.json', 'grunt-aws.json']
highlighter: rouge
gems:
  - jekyll-redirect-from

cartodb-baseurl: 'http://cartodb.com'
academy-baseurl: 'http://academy.cartodb.com'
blog-baseurl: 'http://blog.cartodb.com'
github-baseurl: 'http://github.com/CartoDB/cartodb'
twitter-baseurl: 'https://twitter.com/cartodb'
facebook-baseurl: 'https://www.facebook.com/CartoDB'
linkedin-baseurl: 'https://www.linkedin.com/company/cartodb'

analytics_property_id: ''
hubspot_id: '474999'

collections:
  tutorials:
    output: true
  cartodb-platform:
    output: true

defaults:
  -
    scope:
      path: ""
      type: cartodb-platform
    values:
      js_asset: "editor"
      layout: platform_item
  -
    scope:
      path: ""
      type: tutorials
    values:
      tags: "cartodb, learning, tutorials, documentation, advanced, geospatial, functions"
      js_asset: "index"
